services:
  system-monitor:
    build: .
    container_name: pi-system-monitor
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true # Required for full system access
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
